import React from 'react';
import { 
  Dialog, 
  DialogTitle, 
  DialogContent, 
  DialogActions,
  Box,
  Typography,
  IconButton,
  Button,
  Grid,
  Paper,
  Chip
} from '@mui/material';
import { 
  X, 
  ThumbsUp, 
  ThumbsDown, 
  Target, 
  TrendingUp, 
  AlertCircle, 
  FileText, 
  Download, 
  CheckCircle2 
} from 'lucide-react';
import { alpha, useTheme } from '@mui/material/styles';
import type { Report } from '../../services/report.service';

interface ReportDetailsModalProps {
  isOpen: boolean;
  onClose: () => void;
  report: Report | null;
  onDownloadPdf: (id: number) => void;
  onDownloadCsv: (id: number) => void;
}

export const ReportDetailsModal = ({ isOpen, onClose, report, onDownloadPdf, onDownloadCsv }: ReportDetailsModalProps) => {
  const theme = useTheme();
  
  if (!report) return null;

  const positiveThemes = report.themes.filter(t => t.type === 'POSITIVE');
  const negativeThemes = report.themes.filter(t => t.type === 'NEGATIVE');

  return (
    <Dialog 
      open={isOpen} 
      onClose={onClose}
      maxWidth="md"
      fullWidth
      slotProps={{ paper: {
        sx: {
          borderRadius: 3,
          backgroundColor: alpha(theme.palette.background.paper, 0.95),
          backdropFilter: 'blur(10px)',
          backgroundImage: 'none',
        }
      } }}
    >
      <DialogTitle sx={{ 
        m: 0, p: 3, display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start',
        borderBottom: '1px solid', borderColor: 'divider'
      }}>
        <Box>
          <Box sx={{ display: 'flex', gap: 1, mb: 1, alignItems: 'center' }}>
            <Chip 
              label={report.region} 
              size="small" 
              sx={{ bgcolor: alpha(theme.palette.primary.main, 0.1), color: 'primary.main', fontWeight: 600 }} 
            />
            <Typography variant="body2" color="text.secondary">
              {new Date(report.year, report.month - 1).toLocaleString('default', { month: 'long', year: 'numeric' })}
            </Typography>
          </Box>
          <Typography variant="h5" color="text.primary" sx={{ fontWeight: 700 }}>
            Sentiment Analysis Report
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ display: 'flex', alignItems: 'center', gap: 1, mt: 0.5 }}>
            <FileText size={16} /> Generated by AI on {new Date(report.generatedAt).toLocaleDateString()}
          </Typography>
        </Box>
        <IconButton
          aria-label="close"
          onClick={onClose}
          sx={{ color: 'text.secondary' }}
        >
          <X />
        </IconButton>
      </DialogTitle>
      
      <DialogContent dividers sx={{ p: 3, backgroundColor: alpha(theme.palette.background.default, 0.5) }}>
        
        {/* Score Cards */}
        <Grid container spacing={2} sx={{ mb: 4 }}>
          <Grid size={{ xs: 12, sm: 3 }}>
            <Paper elevation={0} sx={{ p: 2, textAlign: 'center', border: '1px solid', borderColor: 'divider', height: '100%' }}>
              <Typography variant="h3" color="text.primary" sx={{ fontWeight: 700, mb: 0.5 }}>{report.overallScore}<Typography component="span" variant="h5" color="text.secondary">/100</Typography></Typography>
              <Typography variant="caption" color="text.secondary" sx={{ textTransform: 'uppercase', fontWeight: 600, letterSpacing: 1 }}>Overall Score</Typography>
            </Paper>
          </Grid>
          <Grid size={{ xs: 12, sm: 3 }}>
            <Paper elevation={0} sx={{ p: 2, textAlign: 'center', bgcolor: alpha(theme.palette.success.main, 0.1), border: '1px solid', borderColor: alpha(theme.palette.success.main, 0.2), height: '100%' }}>
              <Typography variant="h3" color="success.main" sx={{ fontWeight: 700, mb: 0.5 }}>{report.positivePercentage}%</Typography>
              <Typography variant="caption" color="success.main" sx={{ textTransform: 'uppercase', fontWeight: 600, letterSpacing: 1, opacity: 0.8 }}>Positive</Typography>
            </Paper>
          </Grid>
          <Grid size={{ xs: 12, sm: 3 }}>
            <Paper elevation={0} sx={{ p: 2, textAlign: 'center', bgcolor: alpha(theme.palette.warning.main, 0.1), border: '1px solid', borderColor: alpha(theme.palette.warning.main, 0.2), height: '100%' }}>
              <Typography variant="h3" color="warning.dark" sx={{ fontWeight: 700, mb: 0.5 }}>{report.neutralPercentage}%</Typography>
              <Typography variant="caption" color="warning.dark" sx={{ textTransform: 'uppercase', fontWeight: 600, letterSpacing: 1, opacity: 0.8 }}>Neutral</Typography>
            </Paper>
          </Grid>
          <Grid size={{ xs: 12, sm: 3 }}>
            <Paper elevation={0} sx={{ p: 2, textAlign: 'center', bgcolor: alpha(theme.palette.error.main, 0.1), border: '1px solid', borderColor: alpha(theme.palette.error.main, 0.2), height: '100%' }}>
              <Typography variant="h3" color="error.main" sx={{ fontWeight: 700, mb: 0.5 }}>{report.negativePercentage}%</Typography>
              <Typography variant="caption" color="error.main" sx={{ textTransform: 'uppercase', fontWeight: 600, letterSpacing: 1, opacity: 0.8 }}>Negative</Typography>
            </Paper>
          </Grid>
        </Grid>

        {/* Executive Summary */}
        <Box sx={{ mb: 4 }}>
          <Typography variant="h6" color="text.primary" sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 2 }}>
            <Target size={20} color={theme.palette.primary.main} /> Executive Summary
          </Typography>
          <Paper elevation={0} sx={{ p: 3, border: '1px solid', borderColor: 'divider', bgcolor: 'background.paper' }}>
            <Typography variant="body2" color="text.primary" sx={{ lineHeight: 1.7 }}>
              {report.executiveSummary}
            </Typography>
          </Paper>
        </Box>

        {/* Themes */}
        <Grid container spacing={3} sx={{ mb: 4 }}>
          <Grid size={{ xs: 12, md: 6 }}>
            <Typography variant="h6" color="text.primary" sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 2 }}>
              <ThumbsUp size={20} color={theme.palette.success.main} /> Positive Themes
            </Typography>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5 }}>
              {positiveThemes.length > 0 ? positiveThemes.map(t => (
                <Box key={t.id} sx={{ display: 'flex', alignItems: 'flex-start', gap: 1.5, p: 1.5, bgcolor: alpha(theme.palette.success.main, 0.05), borderRadius: 2, border: '1px solid', borderColor: alpha(theme.palette.success.main, 0.1) }}>
                  <CheckCircle2 size={18} color={theme.palette.success.main} style={{ marginTop: 2, flexShrink: 0 }} />
                  <Typography variant="body2" color="text.primary">{t.theme}</Typography>
                </Box>
              )) : (
                <Typography variant="body2" color="text.secondary" sx={{ fontStyle: 'italic' }}>No positive themes identified.</Typography>
              )}
            </Box>
          </Grid>

          <Grid size={{ xs: 12, md: 6 }}>
            <Typography variant="h6" color="text.primary" sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 2 }}>
              <ThumbsDown size={20} color={theme.palette.error.main} /> Areas for Improvement
            </Typography>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5 }}>
              {negativeThemes.length > 0 ? negativeThemes.map(t => (
                <Box key={t.id} sx={{ display: 'flex', alignItems: 'flex-start', gap: 1.5, p: 1.5, bgcolor: alpha(theme.palette.error.main, 0.05), borderRadius: 2, border: '1px solid', borderColor: alpha(theme.palette.error.main, 0.1) }}>
                  <AlertCircle size={18} color={theme.palette.error.main} style={{ marginTop: 2, flexShrink: 0 }} />
                  <Typography variant="body2" color="text.primary">{t.theme}</Typography>
                </Box>
              )) : (
                <Typography variant="body2" color="text.secondary" sx={{ fontStyle: 'italic' }}>No negative themes identified.</Typography>
              )}
            </Box>
          </Grid>
        </Grid>

        {/* Recommendations */}
        <Box>
          <Typography variant="h6" color="text.primary" sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 2 }}>
            <TrendingUp size={20} color={theme.palette.primary.main} /> AI Recommendations
          </Typography>
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
            {report.recommendations.map((rec, idx) => (
              <Paper elevation={0} key={rec.id} sx={{ p: 2, display: 'flex', alignItems: 'flex-start', gap: 2, border: '1px solid', borderColor: alpha(theme.palette.primary.main, 0.2), bgcolor: alpha(theme.palette.primary.main, 0.02) }}>
                <Box sx={{ 
                  width: 24, height: 24, borderRadius: '50%', bgcolor: alpha(theme.palette.primary.main, 0.1), color: 'primary.main',
                  display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold', fontSize: '0.75rem', flexShrink: 0
                }}>
                  {idx + 1}
                </Box>
                <Typography variant="body2" color="text.primary" sx={{ lineHeight: 1.6 }}>
                  {rec.recommendation}
                </Typography>
              </Paper>
            ))}
          </Box>
        </Box>
        
        {/* Question-wise Analysis */}
        {report.questionAnalysis && report.questionAnalysis.length > 0 && (
          <Box sx={{ mt: 4 }}>
            <Typography variant="h6" color="text.primary" sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 2 }}>
              <FileText size={20} color={theme.palette.secondary.main} /> Question-by-Question Analysis
            </Typography>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              {report.questionAnalysis.map((qa, idx) => (
                <Paper elevation={0} key={qa.id || idx} sx={{ p: 2.5, border: '1px solid', borderColor: 'divider', bgcolor: 'background.paper', borderRadius: 2 }}>
                  <Typography variant="subtitle1" color="text.primary" sx={{ fontWeight: 600, mb: 1.5, display: 'flex', gap: 1.5 }}>
                    <Box component="span" sx={{ color: 'text.secondary' }}>Q.</Box>
                    {qa.questionText}
                  </Typography>
                  
                  <Box sx={{ display: 'flex', width: '100%', height: 12, borderRadius: 6, overflow: 'hidden', mb: 2 }}>
                    <Box sx={{ width: `${qa.positivePercentage}%`, bgcolor: theme.palette.success.main }} title={`Positive: ${qa.positivePercentage}%`} />
                    <Box sx={{ width: `${qa.neutralPercentage}%`, bgcolor: theme.palette.warning.main }} title={`Neutral: ${qa.neutralPercentage}%`} />
                    <Box sx={{ width: `${qa.negativePercentage}%`, bgcolor: theme.palette.error.main }} title={`Negative: ${qa.negativePercentage}%`} />
                  </Box>
                  
                  <Box sx={{ display: 'flex', gap: 3, mb: 2 }}>
                    <Typography variant="body2" sx={{ color: 'success.main', fontWeight: 600 }}>{qa.positivePercentage}% Positive</Typography>
                    <Typography variant="body2" sx={{ color: 'warning.dark', fontWeight: 600 }}>{qa.neutralPercentage}% Neutral</Typography>
                    <Typography variant="body2" sx={{ color: 'error.main', fontWeight: 600 }}>{qa.negativePercentage}% Negative</Typography>
                  </Box>
                  
                  <Typography variant="body2" color="text.secondary" sx={{ fontStyle: 'italic', bgcolor: alpha(theme.palette.secondary.main, 0.05), p: 1.5, borderRadius: 1 }}>
                    <Box component="span" sx={{ fontWeight: 600, color: 'text.primary', mr: 1, fontStyle: 'normal' }}>Summary:</Box>
                    {qa.summary}
                  </Typography>
                </Paper>
              ))}
            </Box>
          </Box>
        )}

      </DialogContent>
      
      <DialogActions sx={{ p: 3, display: 'flex', justifyContent: 'space-between', bgcolor: 'background.paper' }}>
        <Typography variant="body2" color="text.secondary">
          Participation Rate: <Box component="span" sx={{ fontWeight: 600, color: 'text.primary' }}>{report.participationRate.toFixed(1)}%</Box>
        </Typography>
        <Box sx={{ display: 'flex', gap: 2 }}>
          <Button 
            variant="outlined" 
            color="inherit" 
            onClick={() => onDownloadCsv(report.id)}
            startIcon={<Download size={18} />}
            sx={{ borderColor: 'divider' }}
          >
            CSV Export
          </Button>
          <Button 
            variant="contained" 
            color="primary" 
            onClick={() => onDownloadPdf(report.id)}
            startIcon={<Download size={18} />}
          >
            Download PDF
          </Button>
        </Box>
      </DialogActions>
    </Dialog>
  );
};

